apiVersion: apps/v1
kind: Deployment
metadata:
  name: htfrontend
  labels:
    app: HTFE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: HTFE
  template:
    metadata:
      labels:
        app: HTFE
    spec:
      nodeSelector:
        external-apps: "true"
      containers:
      - name: htfrontend
        env:
        - name: FLASK_ENV
          value: "development"
        - name: FLASK_HOST_IP
          value: "0.0.0.0"
        - name: FLASK_HOST_PORT
          value: "5002"
        - name: BE_IP_ADDR
          value: "ht-be:5001"
        image: aliartiza75/ht-fe:0.0.2 # {"$imagepolicy": "<namespace>:<image-policy-name>"}
        ports:
        - containerPort: 5002
