---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ht-fe
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 256m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: 120s
    nginx.ingress.kubernetes.io/proxy-read-timeout: 60s
    kubernetes.io/ingress.class: "nginx-external"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - ht-fe.domain.com
    secretName: ht-fe.domain.com
  rules:
  - host: ht-fe.domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ht-fe
            port: 
              number: 80                               
