---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ht-fe
  annotations:
spec:
  ingressClassName: nginx-external
  rules:
  - host: ht-fe.domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ht-fe
            port: 
              number: 5002                              
