apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: htfrontend
  namespace: default
spec:
  imageRepositoryRef:
    name: htfrontend
  filterTags:
    pattern: '^^v(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc

